# Generated by Django 4.1 on 2022-09-03 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('roster', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpersonnel',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='staff.staff', to_field='id'),
        ),
        migrations.AddField(
            model_name='shift',
            name='roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='roster.roster', to_field='id'),
        ),
        migrations.AddField(
            model_name='rostersheet',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='roster.batch'),
        ),
        migrations.AddField(
            model_name='rostersheet',
            name='roster_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='roster.rosterday', to_field='id'),
        ),
        migrations.AddField(
            model_name='rostersheet',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='roster.shift'),
        ),
        migrations.AddField(
            model_name='rosterday',
            name='roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='roster.roster', to_field='id'),
        ),
        migrations.AddField(
            model_name='roster',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.account', to_field='id'),
        ),
        migrations.AddField(
            model_name='batch',
            name='roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='roster.roster', to_field='id'),
        ),
    ]
