# Generated by Django 4.1 on 2022-08-23 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='subject',
            new_name='title',
        ),
    ]
