# Generated by Django 4.1 on 2022-09-03 07:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reservation_code', models.CharField(blank=True, max_length=64)),
                ('reservation_date', models.DateTimeField(blank=True, null=True)),
                ('number_guests', models.IntegerField(blank=True)),
                ('number_tables', models.IntegerField(blank=True)),
                ('arrival_date', models.DateTimeField(blank=True, null=True)),
                ('reservation_status', models.CharField(blank=True, max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.account', to_field='id')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customer', to_field='id')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
