# Generated by Django 4.1 on 2022-09-07 13:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
        ('reservations', '0002_reservation_customer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationTable',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reservations.reservation', to_field='id')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tables.table', to_field='id')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
