# Generated by Django 4.1 on 2022-09-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rink',
            name='comment',
            field=models.TextField(blank=True, null='True'),
        ),
    ]
