# Generated by Django 4.1 on 2022-09-07 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='customer_location',
            new_name='delivery_location',
        ),
    ]
