# Generated by Django 4.1 on 2022-08-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskitem',
            name='priority',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
