# Generated by Django 4.1 on 2022-09-03 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('adminx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.account', to_field='id'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='access_level',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.account', to_field='id'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='personal_id',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='personal_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.account', to_field='id'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='invitation_status',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='invitee_id',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='invitee_name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
