# Generated by Django 4.1 on 2022-09-12 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminx', '0002_alter_access_account_alter_accountuser_access_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='date_sent',
        ),
    ]
