# Generated by Django 4.1 on 2022-09-13 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem_image'),
        ('orders', '0002_order_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.menuitem', to_field='id'),
        ),
    ]
