# Generated by Django 4.1 on 2022-09-06 05:41

from django.db import migrations, models
import modules.menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=modules.menu.models.item_iamge_upload_path),
        ),
    ]
